### ISSUE TITLE
Creating package for prior version.

### ISSUE THREAD

**Issue by KelSolaar** [conda-forge/colour-science-feedstock#10]
Issue:

Hi @conda-forge/core: Looking at https://anaconda.org/conda-forge/colour-science/files, I see that version 0.3.14 is missing, is building an old version retroactively a thing?

**Comment by CJ-Wright** [comment]
It can be a thing, usually this is done by creating a new branch on the feedstock with the name of the version (for instance `0.3.x` if this was going to handle all bug fixes to `0.3`) and the correct `meta.yaml` and such.

**Comment by thomasmansencal** [comment]
Ah sweet, I will give it a go!

**Comment by thomasmansencal** [comment]
So it seems like the build passes: https://github.com/conda-forge/colour-science-feedstock/pull/11

Should it be merged on top of master in that case?

**Comment by CJ-Wright** [comment]
No, it needs get its own branch

**Comment by thomasmansencal** [comment]
Ok! Just pushed it.

**Comment by CJ-Wright** [comment]
Where did you push it?

**Comment by thomasmansencal** [comment]
Should be here: https://github.com/conda-forge/colour-science-feedstock/tree/0.3.14

**Comment by CJ-Wright** [comment]
sorry for some reason it wasn't showing up before, now it is
